# Generated by Django 4.1.9 on 2023-06-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtdeAlimentoPeixe', models.IntegerField(verbose_name='AlimentoPeixe')),
                ('limpezaAgua', models.CharField(max_length=40, verbose_name='LimpezaAgua')),
                ('peixeMorto', models.CharField(max_length=40, verbose_name='PeixeMorto')),
                ('capacidadeTanque', models.FloatField(verbose_name='CapacidadeTanque')),
                ('nomeCliente', models.CharField(max_length=75, verbose_name='Cliente')),
                ('statusTanque', models.CharField(max_length=75, verbose_name='Status')),
                ('valorAlface', models.FloatField(verbose_name='ValorAlface')),
                ('valorPeixe', models.FloatField(verbose_name='ValorPeixe')),
                ('dataInspecao', models.DateField(verbose_name='Data')),
                ('idCliente', models.IntegerField(verbose_name='IdCliente')),
                ('idTanque', models.IntegerField(verbose_name='IdTanque')),
                ('qtdeAgua', models.FloatField(verbose_name='qtdeAgua')),
                ('qtdeAlfaceColhida', models.IntegerField(verbose_name='AlfaceColhido')),
                ('qtdeAlfacePlantada', models.IntegerField(verbose_name='AlfacePlantado')),
                ('qtdeAlfaceTotal', models.IntegerField(verbose_name='TotalAlfaceColhido')),
                ('qtdePeixesTanque', models.IntegerField(verbose_name='PeixesNoTanque')),
            ],
            options={
                'db_table': 'AquaDash',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
