# Generated by Django 4.1.9 on 2023-05-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashAquaponia', '0003_alter_usermodel_options_alter_usermodel_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=10000, unique=True),
        ),
    ]
